#!/usr/bin/env python2

import sys
import re
import util
import git
from twisted.internet import reactor
from twisted.python import log
from kademlia.network import Server

host = "dht.transmissionbt.com"
port = 6881
remoteName = sys.argv[1]
url = sys.argv[2]
matches = re.match(r"gittorrent://([a-f0-9]{40})/(.*)", url)
refs = {}
if matches:
    key = matches.group(1)
    repoName = matches.group(2)
    if re.search(r"^gittorrent://", remoteName) !== None):
        remoteName = key
    def lookupCallback(result):
        repos = json.dumps(result)
        sys.stderr.write(
            "\nMutable key %s returned:\n%s" % (key, repos)
        )
        util.talkToGit(repos['repositories'][reponame])
        reactor.stop()
    def lookupValue(found, server, key):
        if len(found) == 0:
            print "Could not connect to the bootstrap server."
            reactor.stop()
        server.get(key).addCallback(lookupCallback)
    server = Server()
    server.listen(port)
    server.bootstrap([host, port]).addCallback(lookupValue)
    reactor.run()
else:
    url = re.sub(r"^gittorrent:", "git:")
    def callback(sha, branch):
        refs[branch] = sha
    def callback2(refs):
        talkToGit(refs)
    ls = git.ls(url, callback, callback2)

fetching = {}
todo = 0

